#-------------------------------------------------------------------
# modified from https://bitbucket.org/dark_sylinc/dergo-blender/src/bd5199ee77e5d7325c84f984a33c28f2d744c2ec/DERGO_Server/CMake/Dependencies/OGRE.cmake?at=default&fileviewer=file-view-default
#-------------------------------------------------------------------

macro( setupMyGUI MYGUI_SOURCE, MYGUI_BINARIES, MYGUI_LIBRARIES, MYGUI_INCLUDE_DIRS)

	# Guess the paths.
	set( MYGUI_SOURCE "${CMAKE_SOURCE_DIR}/Dependencies/MyGUI" CACHE STRING "Path to MYGUI source code " )
	if( WIN32 )
		set( MYGUI_BINARIES "${MYGUI_SOURCE}/build" CACHE STRING "Path to MYGUI's build folder generated by CMake" )
		link_directories( "${MYGUI_BINARIES}/lib/$(ConfigurationName)" )
	else()
		set( MYGUI_BINARIES "${MYGUI_SOURCE}/build/${CMAKE_BUILD_TYPE}" CACHE STRING "Path to MYGUI's build folder generated by CMake" )
		link_directories( "${MYGUI_BINARIES}/lib" )
	endif()

	set(${MYGUI_INCLUDE_DIRS} "${MYGUI_SOURCE}/MyGUIEngine/include;${${MYGUI_INCLUDE_DIRS}}")
	set(${MYGUI_INCLUDE_DIRS} "${MYGUI_SOURCE}/Common/Base;${${MYGUI_INCLUDE_DIRS}}")
	set(${MYGUI_INCLUDE_DIRS} "${MYGUI_SOURCE}/Platforms/Ogre2/Ogre2Platform/include;${${MYGUI_INCLUDE_DIRS}}")

	set( MYGUI_LIBRARIES
		debug MyGUIEngine_d debug MyGUI.Ogre2Platform_d
		optimized MyGUIEngine optimized MyGUI.Ogre2Platform
		)
	MESSAGE(STATUS "set ${MYGUI_INCLUDE_DIRS}: ${${MYGUI_INCLUDE_DIRS}}")
	MESSAGE(STATUS "set ${MYGUI_LIBRARIES}: ${${MYGUI_LIBRARIES}}")

endmacro()
