macro(setupMyGUI)
    # Guess the paths.
    set(MYGUI_SOURCE "${CMAKE_SOURCE_DIR}/dependencies/MyGUI" CACHE STRING "Path to MYGUI source code " )
    if( WIN32 )
        set(MYGUI_BINARIES "${MYGUI_SOURCE}/build/gcc/${CMAKE_BUILD_TYPE}" CACHE STRING "Path to MYGUI's build folder generated by CMake" )
        link_directories( "${MYGUI_BINARIES}/lib" )
    else()
        set(MYGUI_BINARIES "${MYGUI_SOURCE}/build/gcc/${CMAKE_BUILD_TYPE}" CACHE STRING "Path to MYGUI's build folder generated by CMake" )
        link_directories( "${MYGUI_BINARIES}/lib" )
    endif()

    list(APPEND MYGUI_INCLUDE_DIRS ${MYGUI_SOURCE}/MyGUIEngine/include)
    list(APPEND MYGUI_INCLUDE_DIRS ${MYGUI_SOURCE}/Platforms/Ogre2/Ogre2Platform/include)

    set(MYGUI_COMMON_INCLUDE_DIRS ${MYGUI_SOURCE}/Common)
    list(APPEND MYGUI_COMMON_INCLUDE_DIRS ${MYGUI_SOURCE}/Common/Base)
    list(APPEND MYGUI_COMMON_INCLUDE_DIRS ${MYGUI_SOURCE}/Common/Base/Ogre2)
    list(APPEND MYGUI_COMMON_INCLUDE_DIRS ${MYGUI_SOURCE}/Common/Input/OIS)

    set( MYGUI_LIBRARIES
        debug MyGUIEngine_d debug MyGUI.Ogre2Platform_d
        optimized MyGUIEngine optimized MyGUI.Ogre2Platform
        )
    set(MYGUI_COMMON_LIBRARIES
        debug ${MYGUI_BINARIES}/lib/libCommon_d.a
        optimized ${MYGUI_BINARIES}/lib/libCommon.a
        )
endmacro()
